name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier check
      run: npm run format:check

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm run test:ci

    - name: Build application
      run: npm run build

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: success()

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t lastName_firstName_coding_assignment13 .

    - name: Test Docker container
      run: |
        docker run -d -p 8018:8018 --name test-container lastName_firstName_coding_assignment13
        sleep 10
        curl -f http://localhost:8018 || exit 1
        docker stop test-container